# Generated by Django 5.2.5 on 2025-09-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieID', models.CharField(max_length=20, unique=True)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(blank=True, max_length=120)),
                ('Actor2Name', models.CharField(blank=True, max_length=120)),
                ('DirectorName', models.CharField(blank=True, max_length=120)),
                ('MovieGenre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi')], max_length=20)),
                ('ReleaseYear', models.PositiveIntegerField()),
            ],
        ),
    ]
